#!/usr/bin/env python3
"""Recompute the log from its entries, and keep LOG.md honest.

    python3 render/stats.py              # print the report
    python3 render/stats.py --write      # rewrite LOG.md from the entries
    python3 render/stats.py --fix        # rewrite stored per-day totals too

Items are the source of truth. The `totals` block in an entry is a
convenience for whatever reads the JSON without summing; `--fix` re-derives
it. The number Luke actually steers by is the rolling 7-day average, so it
gets a column of its own next to every day.
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import entry as E  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOG_MD = os.path.join(ROOT, "LOG.md")
SHEETS_DIR = os.path.join(ROOT, "sheets")

WINDOW = 7


def _num(n):
    return "{:,}".format(int(round(n)))


def _signed(n, unit=""):
    n = int(round(n))
    return "%s%d%s" % ("+" if n > 0 else "−" if n < 0 else "±", abs(n), unit)


def rolling(entries, i, window=WINDOW):
    """Trailing average over the last `window` logged days ending at i."""
    span = entries[max(0, i - window + 1):i + 1]
    n = float(len(span))
    return {k: sum(e["totals"][k] for e in span) / n for k in E.MACROS}, len(span)


def sheets_for(date):
    """Every sheet on disk for a day, newest status first."""
    out = []
    for status in ("final", "open", "plan"):
        for ext in ("png", "pdf"):
            name = "%s-%s.%s" % (date, status, ext)
            if os.path.exists(os.path.join(SHEETS_DIR, name)):
                out.append((status, ext, "sheets/" + name))
    return out


def drift(entries):
    """Days whose stored totals disagree with their items."""
    bad = []
    for e in entries:
        stored = e.get("_stored_totals")
        if stored and any(stored.get(k) != e["totals"][k] for k in E.MACROS):
            bad.append((e["date"], stored, e["totals"]))
    return bad


def load_with_stored(entries_dir=None):
    import json
    entries = []
    for date in E.all_dates(entries_dir):
        path = E.entry_path(date, entries_dir)
        with open(path) as fh:
            raw = json.load(fh)
        e = E.normalize(raw, date=date, entries_dir=entries_dir)
        e["_stored_totals"] = raw.get("totals")
        entries.append(e)
    return entries


def report(entries):
    lines = []
    if not entries:
        return "No entries yet."

    closed = [e for e in entries if e["status"] == "final"]
    avg, n = rolling(entries, len(entries) - 1)
    t = entries[-1]["targets"]

    lines.append("%d day%s logged: %s → %s (%d closed)"
                 % (len(entries), "" if len(entries) == 1 else "s",
                    entries[0]["date"], entries[-1]["date"], len(closed)))
    lines.append("")
    lines.append("Last %d day%s   %s cal · %d P · %d F · %d C"
                 % (n, "" if n == 1 else "s", _num(avg["cal"]),
                    round(avg["p"]), round(avg["f"]), round(avg["c"])))
    lines.append("Versus target  %s cal · %s P · %s F · %s C"
                 % (_signed(avg["cal"] - t["cal"]), _signed(avg["p"] - t["p"]),
                    _signed(avg["f"] - t["f"]), _signed(avg["c"] - t["c"])))
    lines.append("")

    hit_p = sum(1 for e in closed if e["totals"]["p"] >= e["targets"]["p"])
    over_c = sum(1 for e in closed if e["totals"]["c"] > e["targets"]["c"])
    under_f = sum(1 for e in closed if e["totals"]["f"] <= e["targets"]["f"])
    if closed:
        lines.append("Protein target hit on %d of %d closed days." % (hit_p, len(closed)))
        lines.append("Carbs over on %d, fat inside the ceiling on %d."
                     % (over_c, under_f))

    bad = drift(entries)
    if bad:
        lines.append("")
        lines.append("Stored totals disagree with items on %d day%s (run --fix):"
                     % (len(bad), "" if len(bad) == 1 else "s"))
        for date, stored, real in bad:
            lines.append("  %s  stored %s → items %s"
                         % (date, E.totals_value(stored), E.totals_value(real)))
    return "\n".join(lines)


def log_md(entries):
    t = entries[-1]["targets"] if entries else E.DEFAULT_TARGETS
    out = []
    out.append("# Food log")
    out.append("")
    out.append("<!-- Generated by render/stats.py. Edit entries/, not this file. -->")
    out.append("")
    out.append("Cut: 195 lb → 180 lb, no exercise-calorie adjustments. Daily target "
               "**%d P / %d F / %d C** (≈ %s cal). The grams are the contract; "
               "calories are informational. Cooked weights everywhere."
               % (t["p"], t["f"], t["c"], _num(t["cal"])))
    out.append("")

    if not entries:
        out.append("No days logged yet.")
        return "\n".join(out) + "\n"

    out.append("## Days")
    out.append("")
    out.append("| Day | Date | Weekday | Status | Cal | P | F | C | 7-day cal | 7-day P | Sheet |")
    out.append("|---:|---|---|---|---:|---:|---:|---:|---:|---:|---|")
    for i, e in enumerate(entries):
        avg, _ = rolling(entries, i)
        links = " · ".join(
            "[%s](%s)" % (ext, rel) for status, ext, rel in sheets_for(e["date"])
        ) or "—"
        out.append(
            "| %d | %s | %s | %s | %s | %d | %d | %d | %s | %d | %s |"
            % (e["day"], e["date"], e["weekday"].capitalize(), e["status"],
               _num(e["totals"]["cal"]), e["totals"]["p"], e["totals"]["f"],
               e["totals"]["c"], _num(avg["cal"]), round(avg["p"]), links)
        )
    out.append("")

    avg, n = rolling(entries, len(entries) - 1)
    out.append("## The weekly average")
    out.append("")
    out.append("The morning scale plus this block is the whole feedback loop.")
    out.append("")
    out.append("| Window | Days | Cal | P | F | C |")
    out.append("|---|---:|---:|---:|---:|---:|")
    out.append("| Last %d | %d | %s | %d | %d | %d |"
               % (WINDOW, n, _num(avg["cal"]), round(avg["p"]),
                  round(avg["f"]), round(avg["c"])))
    all_avg = {k: sum(e["totals"][k] for e in entries) / float(len(entries))
               for k in E.MACROS}
    out.append("| All time | %d | %s | %d | %d | %d |"
               % (len(entries), _num(all_avg["cal"]), round(all_avg["p"]),
                  round(all_avg["f"]), round(all_avg["c"])))
    out.append("| Target | — | %s | %d | %d | %d |"
               % (_num(t["cal"]), t["p"], t["f"], t["c"]))
    out.append("| Last %d vs target | — | %s | %s | %s | %s |"
               % (WINDOW, _signed(avg["cal"] - t["cal"]), _signed(avg["p"] - t["p"]),
                  _signed(avg["f"] - t["f"]), _signed(avg["c"] - t["c"])))
    out.append("")

    closed = [e for e in entries if e["status"] == "final"]
    if closed:
        hit_p = sum(1 for e in closed if e["totals"]["p"] >= e["targets"]["p"])
        over_c = sum(1 for e in closed if e["totals"]["c"] > e["targets"]["c"])
        under_f = sum(1 for e in closed if e["totals"]["f"] <= e["targets"]["f"])
        out.append("Across %d closed day%s: protein target hit %d, carbs over %d, "
                   "fat inside the ceiling %d."
                   % (len(closed), "" if len(closed) == 1 else "s",
                      hit_p, over_c, under_f))
        out.append("")

    return "\n".join(out) + "\n"


def main(argv=None):
    p = argparse.ArgumentParser(description="Food-log stats and LOG.md.")
    p.add_argument("--write", action="store_true", help="rewrite LOG.md")
    p.add_argument("--fix", action="store_true",
                   help="rewrite stored per-day totals from items (implies --write)")
    p.add_argument("--entries-dir", help="read entries from here")
    args = p.parse_args(argv)

    try:
        entries = load_with_stored(args.entries_dir)
    except E.EntryError as exc:
        print("error: %s" % exc, file=sys.stderr)
        return 1

    if args.fix:
        for date, _, _ in drift(entries):
            e = [x for x in entries if x["date"] == date][0]
            E.save(e, args.entries_dir)
            print("fixed totals: %s" % date)
        entries = load_with_stored(args.entries_dir)

    print(report(entries))

    if args.write or args.fix:
        with open(LOG_MD, "w") as fh:
            fh.write(log_md(entries))
        print("\nwrote %s" % os.path.relpath(LOG_MD, os.getcwd()))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
